language: node_js
node_js:
  - '0.12'
branches:
  only:
    - master
script:
  - ./travis.sh
sudo: false
cache:
  directories:
    - node_modules
    - 00-simple-single-page/node_modules
    - 01-history-api/node_modules
    - 02-routing/node_modules
    - 03-service/node_modules
    - 04-infinite-scroll/node_modules
addons:
  sauce_connect: true
env:
  global:
    - secure: "j5nS2L0kqACrfpB1Xjg9KipHHsrUs70arI/Hn8RCAaoM9TPNMedUii13CgxcI8DDjTzY/r0xOLPf71BhN30a2Su5lY1NIkE/WAi9FFJrWabnjjXf8EGxKu1D99wRnEYGPyIqJbdgsL1ihUk5dwOmUfnXgMKszvMgkLhVBsl1NgU="
    - secure: "QTQJflR00Btdl8qJDWdrLxJ3h8tF9B8thWGHRTl6bhscIn6SyeT3xV7lDApE7neyBU3QDTEjSKZPLDVSqUcG0lue37z9NRt9nccFUTYt46zcHB4TcmvWKkI1eci9nNC5tXTtEtvnOB3o5Wu5Ok2vRJGgjQpLqnhbGFGxWPY7awU="
    - secure: "eAbUuj0Hp/HTXAxCEbMabYIknHeAHELUg4fm1fcAioc2t6PjRJiKoaLW6rCv9kpsCPZfcigKMJZmc+ZEdXYLSQVSKdcUB4jQ0Jon1qT6FSObij1K2KAyoHQsOE68sD5cHkXqbciQDXfhgxJ22aTfV4EIEm3jdxd2CG/EHevjR24="
