language: node_js
node_js:
  - '0.11'
script:
  - ./travis.sh
addons:
  sauce_connect: true
env:
  global:
    - secure: "j5nS2L0kqACrfpB1Xjg9KipHHsrUs70arI/Hn8RCAaoM9TPNMedUii13CgxcI8DDjTzY/r0xOLPf71BhN30a2Su5lY1NIkE/WAi9FFJrWabnjjXf8EGxKu1D99wRnEYGPyIqJbdgsL1ihUk5dwOmUfnXgMKszvMgkLhVBsl1NgU="
    - secure: "QTQJflR00Btdl8qJDWdrLxJ3h8tF9B8thWGHRTl6bhscIn6SyeT3xV7lDApE7neyBU3QDTEjSKZPLDVSqUcG0lue37z9NRt9nccFUTYt46zcHB4TcmvWKkI1eci9nNC5tXTtEtvnOB3o5Wu5Ok2vRJGgjQpLqnhbGFGxWPY7awU="
    - secure: "awq+0AKUxuheErIqfEU3fRcQKuTehofEM5eF88p37+c9GgjqFAp7xOg2iBH5GcQovg7+ySIUokmzG5tkAfdQpAWYvqnVOuJdqU4N5doWgDJcQ9736noTJSO/X1k0ClnuDu2p+mUU12VAXnyXsdJmB9p+JRfauUwQV5AzmFplAUM="
